# docker-compose -f keycloak.yml -p keycloak-set up -d
# credenciais keycloak:keycloak
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    restart: always
    ports:
      - 8888:8080
      - 7443:7443      
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: keycloak
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    command:
      ["start-dev"]      
    depends_on:
      - mysql
    networks:
    - database
    
  mysql:
    image: mysql:9.1.0
    container_name: mysql-keycloak
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: keycloak
    ports:
      - "3306:3306"
    volumes:
      - ./volume/mysql:/var/lib/mysql
    networks: 
      - database
          
networks: 
  database:
    driver: bridge 