# docker-compose -f keycloak-federation-openldap-ufmt.yml -p keycloak-federation-openldap-ufmt-set up -d

#version: '3.8'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap-ufmt
    environment:
      - LDAP_ORGANISATION=Universidade Federal de Mato Grosso
      - LDAP_DOMAIN=ufmt.br
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=admin
      - "LDAP_BASE_DN=dc=ufmt,dc=br"
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=readonly
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data_keycloak_federation:/var/lib/ldap
      - ldap_config_keycloak_federation:/etc/ldap/slapd.d
    restart: always
    networks:
      - network_keycloak_federation

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin-ufmt
    depends_on:
      - openldap
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "8089:80"
      - "6443:443"
    restart: always
    networks:
      - network_keycloak_federation

  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data_keycloak_federation:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - network_keycloak_federation

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak-ufmt
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - "8088:8080"
    restart: always
    depends_on:
      - postgres
      - openldap
    networks:
      - network_keycloak_federation

volumes:
  postgres_data_keycloak_federation:
    driver: local
  ldap_data_keycloak_federation:
    driver: local
  ldap_config_keycloak_federation:
    driver: local

networks:
  network_keycloak_federation:
    driver: bridge