# docker-compose -f nexus3.yml -p nexus-set up -d
# criar o diretorio nexus-data e conceder permissão
# chown -R 200 /caminho-diretorio/nexus-data
# Senha: verificar no arvquivo docker-volumes/nexus-data/admin.password


services:
  nexus:
    container_name: nexus3
    image: sonatype/nexus3:3.70.1
    expose:
      - 5021
      - 5022
      - 5023
    ports:
      - "5021:8081"
      - "5022:8082"
      - "5023:8083"
    volumes:
      - ./docker-volumes/nexus-data:/nexus-data
    restart: always
